<?php

use App\Models\UserNavigation;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class UserNavigationSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    $userNavigations = [
      [
        'role_id' => 1,
        'navigation_id' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 2,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 3,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 4,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 5,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 6,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 7,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 8,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 9,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 10,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 11,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 12,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 13,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 14,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 15,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 16,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 17,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 18,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 19,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 20,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 21,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 2,
        'navigation_id' => 1,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 2,
        'navigation_id' => 2,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 2,
        'navigation_id' => 3,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 2,
        'navigation_id' => 4,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 2,
        'navigation_id' => 5,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 2,
        'navigation_id' => 6,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 2,
        'navigation_id' => 7,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 2,
        'navigation_id' => 8,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 2,
        'navigation_id' => 9,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 2,
        'navigation_id' => 10,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 2,
        'navigation_id' => 11,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 2,
        'navigation_id' => 12,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 2,
        'navigation_id' => 13,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 2,
        'navigation_id' => 14,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 2,
        'navigation_id' => 15,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 2,
        'navigation_id' => 16,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 2,
        'navigation_id' => 17,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 2,
        'navigation_id' => 21,
        'create' => 1,
        'update' => 1,
        'delete' => 1,

      ],
      [
        'role_id' => 1,
        'navigation_id' => 22,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 23,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 24,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 25,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 26,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 27,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 28,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 29,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 30,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 31,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 32,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 3,
        'navigation_id' => 13,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 3,
        'navigation_id' => 14,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 3,
        'navigation_id' => 22,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 3,
        'navigation_id' => 23,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 3,
        'navigation_id' => 24,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 3,
        'navigation_id' => 25,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 3,
        'navigation_id' => 26,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 3,
        'navigation_id' => 27,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 3,
        'navigation_id' => 28,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 3,
        'navigation_id' => 29,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 3,
        'navigation_id' => 30,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 3,
        'navigation_id' => 31,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 3,
        'navigation_id' => 32,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 33,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 2,
        'navigation_id' => 31,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 2,
        'navigation_id' => 32,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 2,
        'navigation_id' => 33,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 3,
        'navigation_id' => 34,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ],
      [
        'role_id' => 1,
        'navigation_id' => 34,
        'create' => 1,
        'update' => 1,
        'delete' => 1,
      ]
    ];

    $numId = 1;
    foreach ($userNavigations as &$elem) {
      $elem['id'] = $numId;
      $numId++;
    }

    foreach ($userNavigations as $userNavigation) {
      UserNavigation::updateOrCreate(['id' => $userNavigation['id']], $userNavigation);
    }
  }
}
